# Generated by Django 4.2.11 on 2024-09-22 08:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipeimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
