# Generated by Django 4.2.11 on 2024-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_favourites_options_category_name_az_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
